export const DIALOG_SHOW = 'app/DIALOG_SHOW'
export const DIALOG_HIDE = 'app/DIALOG_HIDE'
export const TOGGLE_DRAWER = 'app/TOGGLE_DRAWER'
export const SHOW_DRAWER = 'app/SHOW_DRAWER'
export const HIDE_DRAWER = 'app/HIDE_DRAWER'
