export const DIALOG_SHOW = 'app/DIALOG_SHOW'
export const DIALOG_HIDE = 'app/DIALOG_HIDE'
export const TOGGLE_DRAWER = 'app/TOGGLE_DRAWER'
export const SHOW_DRAWER = 'app/SHOW_DRAWER'
export const HIDE_DRAWER = 'app/HIDE_DRAWER'
export const TOGGLE_COLLAPSE = 'app/TOGGLE_COLLAPSE'
export const CONTENT_CHANGE = 'app/CONTENT_CHANGE'
export const FETCH_SUCCESS = 'app/FETCH_SUCCESS'
export const FETCH_FAIL = 'app/FETCH_FAIL'
export const FETCH_BEGIN = 'app/FETCH_BEGIN'
export const FETCH_CLEAR = 'app/FETCH_CLEAR'

export const PUSH_PAGE = 'nav/PUSH_PAGE'
